### ISSUE TITLE
Not support for Godot 4.2.2

### ISSUE THREAD

**Issue by cnrdskn** [jesuisse/godot-radial-menu-control#3]
This plugin is just awesome but unfortunately it's not supported by Godot 4.2.2.

**Comment by 4ybaka** [comment]
yeah... do you know what is the latest supported version?

**Comment by cnrdskn** [comment]
I haven't tried it, but it would probably work in Godot 3.x. The error is related to the new arrangement in GDScript. It's annoying because it's not just this plugin; many things, including old tutorials, have become useless due to changes in GDScript. Godot developers should consider creating a bridge for the old GDScript because if they keep changing it repeatedly, it might start to lose its stability over time. If stability is lost, people may start switching to other engines.

**Comment by 4ybaka** [comment]
I checked the migration story and it is a little bit more complicated. The Popup class that is used here changed its hierarchy between v3 and 4. Now it inherits viewport instead of canvasitem. So some internally used methods are not available anymore. I have a branch with fixes for simple issues but I don't think I'll have time to rewrite it's internals on viewport.

**Comment by jesuisse** [comment]
The commits after the commit tagged v1.1 now are updated to work with Godot 4.3.

**Comment by jesuisse** [comment]
Closing this as the plugin was updated to work with Godot 4.3. The code will most likely work with Godot 4.2 as well, but this is untested.

**Comment by jesuisse** [comment]
Closing this as the code was updated to Godot 4.3 and should work with Godot 4.2 as well with no or very minimal changes (possibly in the drawing library script, as some drawing commands have changed from 4.2 to 4.3, but this remains untested).
